# Define the name of the workflow
name: Docker Image CI


# Define the event(s) that will trigger this workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Define the job(s) that this workflow will execute
jobs:

  build:

    # Define the operating system that will run the job
    runs-on: ubuntu-latest

    # Define the steps that this job will execute
    steps:
    - name: Checkout # hämta repo
      uses: actions/checkout@v3

    - name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io # Specify the registry URL
        username: miralee94 # Specify the Docker Hub username
        password: ${{ secrets.SECRET_GITHUB }} # Use a secret to store the Docker Hub password

    # Enable Docker BuildKit
    # Specify the Dockerfile location
    # Tag the Docker image with the specified name and version

    - name: Build & Tag Docker Image
      run: |
        export DOCKER_BUILDKIT=1
        docker build \
          --file ./docker/Dockerfile \
          --tag ghcr.io/miralee94/create_repo:latest .

    # Push all tags of the Docker image to the specified registry
    - name: Push Docker Image
      run: docker image push --all-tags ghcr.io/miralee94/create_repo


